export const COMMON_ACTIONS = {
  GET_DATA_REQUEST: "GET_DATA_REQUEST",
  GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
  GET_DATA_FAILURE: "GET_DATA_FAILURE",

  GET_DETAIL_DATA_REQUEST: "GET_DETAIL_DATA_REQUEST",
  GET_DETAIL_DATA_SUCCESS: "GET_DETAIL_DATA_SUCCESS",
  GET_DETAIL_DATA_FAILURE: "GET_DETAIL_DATA_FAILURE",

  UPDATE_LOADER_REQUEST: "UPDATE_LOADER_REQUEST",

  UPDATE_DATA_REQUEST: "UPDATE_DATA_REQUEST"
};

export const FEEDYARD_ACTIONS = {
  SELECTED_FEEDYAR_REQUEST: "SELECTED_FEEDYAR_REQUEST",
};

export const USER_ACTIONS = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  REFRESH_TOKEN_REQUEST: "REFRESH_TOKEN_REQUEST",
  REFRESH_TOKEN_SUCCESS: "REFRESH_TOKEN_SUCCESS",
  REFRESH_TOKEN_FAILURE: "REFRESH_TOKEN_FAILURE"
};



export const USER_MANAGEMENT_ACTIONS = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  
  GET_ROLES_REQUEST: "GET_ROLES_REQUEST",
  GET_ROLES_SUCCESS: "GET_ROLES_SUCCESS",
  GET_ROLES_FAILURE: "GET_ROLES_FAILURE",

  UPDATE_ROLE_STATUS_REQUEST: "UPDATE_ROLE_STATUS_REQUEST",
  UPDATE_ROLE_STATUS_SUCCESS: "UPDATE_ROLE_STATUS_SUCCESS",
  UPDATE_ROLE_STATUS_FAILURE: "UPDATE_ROLE_STATUS_FAILURE",

  GET_ALL_PERMISSIONS_REQUEST: "GET_ALL_PERMISSIONS_REQUEST",
  GET_ALL_PERMISSIONS_SUCCESS: "GET_ALL_PERMISSIONS_SUCCESS",
  GET_ALL_PERMISSIONS_FAILURE: "GET_ALL_PERMISSIONS_FAILURE",

  ADD_UPDATE_ROLE_REQUEST: "ADD_UPDATE_ROLE_REQUEST",
  ADD_UPDATE_ROLE_SUCCESS: "ADD_UPDATE_ROLE_SUCCESS",
  ADD_UPDATE_ROLE_FAILURE: "ADD_UPDATE_ROLE_FAILURE",

  GET_ROLE_PERMISSIONS_REQUEST: "GET_ROLE_PERMISSIONS_REQUEST",
  GET_ROLE_PERMISSIONS_SUCCESS: "GET_ROLE_PERMISSIONS_SUCCESS",
  GET_ROLE_PERMISSIONS_FAILURE: "GET_ROLE_PERMISSIONS_FAILURE",

  GET_LOCATIONS_REQUEST: "GET_LOCATIONS_REQUEST",
  GET_LOCATIONS_SUCCESS: "GET_LOCATIONS_SUCCESS",
  GET_LOCATIONS_FAILURE: "GET_LOCATIONS_FAILURE",

  ADD_LOCATION_REQUEST: "ADD_LOCATION_REQUEST",
  ADD_LOCATION_SUCCESS: "ADD_LOCATION_SUCCESS",
  ADD_LOCATION_FAILURE: "ADD_LOCATION_FAILURE",

  UPDATE_LOCATION_REQUEST: "UPDATE_LOCATION_REQUEST",
  UPDATE_LOCATION_SUCCESS: "UPDATE_LOCATION_SUCCESS",
  UPDATE_LOCATION_FAILURE: "UPDATE_LOCATION_FAILURE",

  VALIDATE_LOCATION_ID_REQUEST: "VALIDATE_LOCATION_ID_REQUEST",
  VALIDATE_LOCATION_ID_SUCCESS: "VALIDATE_LOCATION_ID_SUCCESS",
  VALIDATE_LOCATION_ID_FAILURE: "VALIDATE_LOCATION_ID_FAILURE",

  UPDATE_LOCATION_STATUS_REQUEST: "UPDATE_LOCATION_STATUS_REQUEST",
  UPDATE_LOCATION_STATUS_SUCCESS: "UPDATE_LOCATION_STATUS_SUCCESS",
  UPDATE_LOCATION_STATUS_FAILURE: "UPDATE_LOCATION_STATUS_FAILURE",

  GET_USERS_REQUEST: "GET_USERS_REQUEST",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAILURE: "GET_USERS_FAILURE",

  ADD_USER_REQUEST: "ADD_USER_REQUEST",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  ADD_USER_FAILURE: "ADD_USER_FAILURE",

  GET_USER_ROLES_REQUEST: "GET_USER_ROLES_REQUEST",
  GET_USER_ROLES_SUCCESS: "GET_USER_ROLES_SUCCESS",
  GET_USER_ROLES_FAILURE: "GET_USER_ROLES_FAILURE",

  UPDATE_USER_STATUS_REQUEST: "UPDATE_USER_STATUS_REQUEST",
  UPDATE_USER_STATUS_SUCCESS: "UPDATE_USER_STATUS_SUCCESS",
  UPDATE_USER_STATUS_FAILURE: "UPDATE_USER_STATUS_FAILURE",

  VALIDATE_USERNAME_REQUEST: "VALIDATE_USERNAME_REQUEST",
  VALIDATE_USERNAME_SUCCESS: "VALIDATE_USERNAME_SUCCESS",
  VALIDATE_USERNAME_FAILURE: "VALIDATE_USERNAME_FAILURE"
};



export const ADMIN_CONFIG = {
  LIST_REQUEST: "ADMIN_LIST_REQUEST",
  LIST_SUCCESS: "ADMIN_LIST_SUCCESS",
  LIST_FAILURE: "ADMIN_LIST_FAILURE",

  DELETE_REQUEST: "ADMIN_DELETE_REQUEST",
  DELETE_SUCCESS: "ADMIN_DELETE_SUCCESS",
  DELETE_FAILURE: "ADMIN_DELETE_FAILURE",

  POST_REQUEST: "ADMIN_POST_REQUEST",
  POST_SUCCESS: "ADMIN_POST_SUCCESS",
  POST_FAILURE: "ADMIN_POST_FAILURE",

  UPDATE_REQUEST: "UPDATE_REQUEST",
  UPDATE_SUCCESS: "UPDATE_SUCCESS",
  UPDATE_FAILURE: "UPDATE_FAILURE",

  DOWNLOAD_PDF_REQUEST:"DOWNLOAD_PDF_REQUEST",
  DOWNLOAD_PDF_SUCCESS:"DOWNLOAD_PDF_SUCCESS",
  DOWNLOAD_PDF_FAILURE:"DOWNLOAD_PDF_FAILURE",
};

